- hosts: kubemaster
  become: true
  become_user: root

  vars_prompt:
    - name: CONFIRM
      prompt: "Running kubemasterplaybook will nuke existing cluster.\n\nType 'Rebuild master' to continue"
      private: false

  vars:
    - destroy: true

  pre_tasks:
    - name: Check if to continue with creating kube.master
      fail:
        msg: "Write 'Rebuild master' if you do want to rebuild kube.master"
      when: CONFIRM != "Rebuild master"

  roles:
    - kubemaster
