---
apiVersion: v1
kind: Service
metadata:
  name: tnrs
  namespace: phylo
  labels:
    app: tnrs
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: {{ TNRS.NODE_PORT }}
      targetPort: 5051
  selector:
    app: tnrs
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tnrs
  namespace: phylo
spec:
  replicas: 3
  template:
    metadata:
      namespace: phylo
      name: tnrs
      labels:
        app: tnrs
        tier: frontend
    spec:
      containers:
        - name: tnrs
          image: phylotastic/name_resolver:v0.0.1
          livenessProbe:
            httpGet:
              path: /phylotastic_ws/tnrs/gnr
              port: 5051
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /phylotastic_ws/tnrs/gnr
              port: 5051
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 5051
              name: http
